export const LOCALIZATION = {
  actions: "Actions",
  clearFilter: "Clear filters",
  clearSearch: "Clear search",
  clearSort: "Clear sorting",
  filterByColumn: "Filter by {column}",
  rowsPerPage: "Rows per page",
  of: "of",
  goToFirstPage: "Go to first page",
  goToLastPage: "Go to last page",
  goToNextPage: "Go to next page",
  goToPreviousPage: "Go to previous page",
  cancel: "Cancel",
  save: "Save",
  noResultsFound: "No results found",
  sortByColumnAsc: "Sort by {column} ascending",
  sortByColumnDesc: "Sort by {column} descending",
  sortedByColumnAsc: "Sorted by {column} ascending",
  sortedByColumnDesc: "Sorted by {column} descending",
  noRecordsToDisplay: "No records to display",
};
